language: python
python:
- '2.7'
- '3.3'
- pypy
sudo: true
before_install:
- ./travis-mecab-install.sh
- export CGO_LDFLAGS="`mecab-config --libs`"
- export CGO_CFLAGS="-I`mecab-config --inc-dir`"
install:
- pip install mecab-python3
script:
- make test
