name: build release binaries

on:
  pull_request:
  release:
    types: [created]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: checkout submodules
        run: |
          git submodule sync --recursive
          git submodule update --init --force --recursive
      - name: setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.14"
      - name: install mecab
        run: |
          .github/install-mecab-linux.sh
      - name: make dictionary
        run: |
          make Grongish.tar.gz

      - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: Grongish.tar.gz
          path: Grongish.tar.gz
      - name: Upload Release Assets
        uses: shogo82148/actions-upload-release-asset@8f6863c6c894ba46f9e676ef5cccec4752723c1e # v1.9.2
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: Grongish.tar.gz
        if: github.event_name == 'release'
