name: build release binaries

on:
  pull_request:
  release:
    types: [created]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: checkout submodules
        run: |
          git submodule sync --recursive
          git submodule update --init --force --recursive
      - name: setup Python
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
        with:
          python-version: "3.13"
      - name: install mecab
        run: |
          .github/install-mecab-linux.sh
      - name: make dictionary
        run: |
          make Grongish.tar.gz

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: Grongish.tar.gz
          path: Grongish.tar.gz
      - name: Upload Release Assets
        uses: shogo82148/actions-upload-release-asset@8482bd769644976d847e96fb4b9354228885e7b4 # v1.7.8
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: Grongish.tar.gz
        if: github.event_name == 'release'
