name: server test

on:
  pull_request: {}
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: build
        run: |
          make docker
        working-directory: server
      - name: test
        run: |
          make test
        working-directory: server
