name: server test

on:
  pull_request: {}
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: build
        run: |
          make docker
        working-directory: server
      - name: test
        run: |
          make test
        working-directory: server
