name: server test

on:
  pull_request: {}
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: build
        run: |
          make docker
        working-directory: server
      - name: test
        run: |
          make test
        working-directory: server
