name: test

on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        python:
          - "3.13"
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: checkout submodules
        run: |
          git submodule sync --recursive
          git submodule update --init --force --recursive
      - name: setup Python ${{ matrix.python }}
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: ${{ matrix.python }}
      - name: install mecab
        run: |
          .github/install-mecab-linux.sh
      - name: test
        run: |
          make test
