name: test

on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        python:
          - "3.13"
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - name: checkout submodules
        run: |
          git submodule sync --recursive
          git submodule update --init --force --recursive
      - name: setup Python ${{ matrix.python }}
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
        with:
          python-version: ${{ matrix.python }}
      - name: install mecab
        run: |
          .github/install-mecab-linux.sh
      - name: test
        run: |
          make test
